
#version 430

layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba32f, binding = 0) uniform image3D voxelGrid; 

void main() {

  ivec3 dims = imageSize(voxelGrid);

  ivec3 voxelCoord = ivec3(gl_GlobalInvocationID.xy, 0); 
  vec4 accum = vec4(0);
  vec4 voxelColor;
  for(int i = 0; i < dims.z; ++i) {
    voxelCoord.z = i; 
    voxelColor = imageLoad(voxelGrid, voxelCoord); 
    accum += voxelColor;
    imageStore(voxelGrid, voxelCoord, accum); 
  }
}
